### ISSUE TITLE
Cambios solicitados

### ISSUE THREAD

**Issue by CarlosRubioTNM** [AdrianMora1/EmptyRepository#2]
Buen trabajo, jóvenes. Ahora requiero que realicen los siguientes cambios:

1. Cambiar los párrafos generados por lorem ipsum por descripciones de los integrantes del equipo.
2. Coloquen la misión y visión (inventadas) de la empresa.
3. Colocar un pie de página con un número de contacto inventado y el año del Copyright del sitio (2022).

Cuando realicen los cambios, me avisan por medio de este hilo. Saludos.

**Comment by AdrianMora1** [comment]
Se hacen las debidas correcciones. Saludos @CarlosRubioTNM
